### ISSUE TITLE
What is the need to install the iproute package?

### ISSUE THREAD

**Issue by phar1no** [giovtorres/ansible-role-lldpad#1]
Could you explain what the iproute package installation is required for?

**Comment by giovtorres** [comment]
When I initially wrote this role, I can't remember if `iproute` was included as a package dependency for `lldpad`.  The `iproute` package is used to populate the `ansible_interfaces` fact, and the test CentOS containers don't have `iproute` pre-installed.

I just checked and `iproute` is only needed during the tests, as `lldpad` pulls in `iproute` as a dependency, but after the facts have already been gathered, so that's why it's needed for the tests in the prepare stage.

I will update the README.  Thank you for the question.
